import { UnityProvider } from '../hooks/useUnity';
import Header from '@/components/Header';

import { Funnel_Sans } from 'next/font/google';
import './globals.css';
import LoadingOverlay from '@/components/LoadingOverlay';

const inter = Funnel_Sans({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata = {
  title: 'EcoSim',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <UnityProvider>
          <LoadingOverlay />
          <Header />
          {children}
        </UnityProvider>
      </body>
    </html>
  );
}
